fix compile warnings with gcc 4.9 (deprecated-declarations, unused-but-set-variable)
replacement for g_strdown(): inplace_ascii_strdown():

  client_lib.c:347:2: error: 'g_strdown' is deprecated (declared at /usr/include/glib-2.0/glib/gstrfuncs.h:207) [-Werror=deprecated-declarations]
  heartbeat.c:568:2: error: ‘g_strdown’ is deprecated (declared at /usr/include/glib-2.0/glib/gstrfuncs.h:207) [-Werror=deprecated-declarations]
  heartbeat.c:4984:4: error: ‘g_strdown’ is deprecated (declared at /usr/include/glib-2.0/glib/gstrfuncs.h:207) [-Werror=deprecated-declarations]
  heartbeat.c:6664:2: error: ‘g_strdown’ is deprecated (declared at /usr/include/glib-2.0/glib/gstrfuncs.h:207) [-Werror=deprecated-declarations]
  config.c:1359:2: error: ‘g_strdown’ is deprecated (declared at /usr/include/glib-2.0/glib/gstrfuncs.h:207) [-Werror=deprecated-declarations]
  config.c:1909:2: error: ‘g_strdown’ is deprecated (declared at /usr/include/glib-2.0/glib/gstrfuncs.h:207) [-Werror=deprecated-declarations]

Very much possible that the current behaviour is not was what intended.
But I'm not going to change behavior now without full understanding of the consequences.
I leave the "finalrc" assignments commented.

  hb_resource.c:1372:6: error: variable ‘finalrc’ set but not used [-Werror=unused-but-set-variable]
  hb_resource.c:1836:8: error: variable ‘finalrc’ set but not used [-Werror=unused-but-set-variable]
  hb_resource.c:2008:7: error: variable ‘finalrc’ set but not used [-Werror=unused-but-set-variable]

These have just been removed now:

  bcast.c:419:22: error: variable 'ei' set but not used [-Werror=unused-but-set-variable]
  ping.c:200:22: error: variable 'to' set but not used [-Werror=unused-but-set-variable]
  heartbeat.c:5874:7: error: variable ‘IsToUs’ set but not used [-Werror=unused-but-set-variable]
  ccmlib_memapi.c:153:7: error: variable 'sockfd' set but not used [-Werror=unused-but-set-variable]
  ccmlib_memapi.c:269:6: error: variable 'trans' set but not used [-Werror=unused-but-set-variable]
  ccmgraph.c:543:15: error: variable ‘numBytes’ set but not used [-Werror=unused-but-set-variable]
  ccm_statemachine.c:481:13: error: variable ‘numbytes’ set but not used [-Werror=unused-but-set-variable]
  ccm_statemachine.c:516:6: error: variable ‘str_len’ set but not used [-Werror=unused-but-set-variable]
  ccm_statemachine.c:567:10: error: variable ‘head’ set but not used [-Werror=unused-but-set-variable]
  ccm_statemachine.c:820:6: error: variable ‘strsize’ set but not used [-Werror=unused-but-set-variable]
  ccm_statemachine.c:898:17: error: variable ‘bitmap_strlen’ set but not used [-Werror=unused-but-set-variable]
  ccm_statemachine.c:3547:25: error: variable ‘strsize’ set but not used [-Werror=unused-but-set-variable]
  ccm_statemachine.c:3547:6: error: variable ‘numBytes’ set but not used [-Werror=unused-but-set-variable]
  drbd-peer-outdater.c:188:13: error: variable ‘src’ set but not used [-Werror=unused-but-set-variable]